### ISSUE TITLE
Array chunking too?

### ISSUE THREAD

**Issue by theScottyJam** [tc39/proposal-iterator-chunking#12]
Should we all add support for chunking arrays? It's also a very common operation to do with arrays, and most of the iterator methods are also on arrays in some form.

**Comment by zloirock** [comment]
#2

**Comment by bakkot** [comment]
> It's also a very common operation to do with arrays

Is it? I don't think I've ever wanted this where the _output_ is an array. I've only ever wanted it for one-shot, in-order consumption of the results (e.g. batching). For which `array.values().chunks(N)` works fine.

Anyway, closing as a duplicate of #2.
