### ISSUE TITLE
what chunk sizes are valid?

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-iterator-chunking#5]
Non-integral and negative chunk sizes should clearly throw.

I think size zero should throw as well. Throwing is much friendlier than potentially getting an infinite iterator, especially when working only with finite iterators. Infinite iterators should be hard to obtain by accident, since they can easily lead to infinite loops. That is, `for (let item of array.values().chunk(N)) /* ... */` should either throw or be a bounded size loop.

**Comment by michaelficarra** [comment]
@lucacasonato made the same point about it being surprising for a chunking operation to turn a finite-size iterator into an infinite one. I agree and find that compelling enough to change my preference for 0-size chunks from infinite empty arrays to throw.

**Comment by michaelficarra** [comment]
Valid chunk sizes are 1 through 2<sup>32</sup>-1, inclusive.
